# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\ExcelServerRepository:
        class: App\Repository\ExcelServerRepository
        arguments:
            - '%kernel.project_dir%/var/data/servers_filters_assignment.xlsx'
            - '@App\Utils\StorageParser'
            - '@App\Utils\RamParser'
            -
    Symfony\Component\Cache\Adapter\FilesystemAdapter: ~

    App\Repository\CachedExcelServerRepository:
        class: App\Repository\CachedExcelServerRepository
        arguments:
            - '@App\Repository\ExcelServerRepository'
            - '@Symfony\Component\Cache\Adapter\FilesystemAdapter'
            - '%kernel.project_dir%/var/data/servers_filters_assignment.xlsx'

    App\Repository\ServerRepositoryInterface:
        alias: App\Repository\CachedExcelServerRepository

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
